@contentType = application/json

### Create Todo
# @name createTodo
POST {{url}}/todos
Content-Type: {{contentType}}

{
  "title": "go to bed at pm.9"
}

### Get Todo
GET {{url}}/todo/{{createTodo.response.body.$.todo_id}}

### Update Todo
PUT {{url}}/todo/{{createTodo.response.body.$.todo_id}}
Content-Type: {{contentType}}

{
  "title": "go to bed at pm.10",
  "completed": true
}

### Delete Todo
DELETE {{url}}/todo/{{createTodo.response.body.$.todo_id}}
